package models.enums;

public enum TypeMessageEnum {
//    Define Error Message
    ERROR_FUND_INVALID,
    ERROR_BILL_NOT_EXISTS,
    ERROR_BILL_INVALID,
    ERROR_BILL_PAY,
    ERROR_ACCOUNT_IS_REQUIRED,
    ERROR_ACCOUNT_NOT_FOUND,
    ERROR_PASSWORD_IS_REQUIRED,
    ERROR_PASSWORD_NOT_MATCH,
    ERROR_PROVIDER_INVALID,
    ERROR_PAYMENT_INVALID,
    ERROR_PAYMENT_EXISTS,

//    Define Question Message
    QUESTION_0,
    QUESTION_1,
    QUESTION_2,
    QUESTION_3,
    QUESTION_4,
    QUESTION_5,
    QUESTION_6,
    QUESTION_7,
    QUESTION_8,
    QUESTION_EXIT,

//  Define Message
    MESSAGE_LOGIN,
    MESSAGE_ACCOUNT,
    MESSAGE_PASSWORD,
    MESSAGE_SUCCESS,
    MESSAGE_ERROR,
    MESSAGE_RETRY,
    ERROR_MENU_NOT_EXISTS,
    MESSAGE_CHOOSE_MENU;

}
